// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDzHpaIfdPnG-A5a6ESchdpQbwSXHgD1EQ',
    appId: '1:985133492222:web:50738a269574f49cde42af',
    messagingSenderId: '985133492222',
    projectId: 'fdtcg-chat-app-with-firebase',
    authDomain: 'fdtcg-chat-app-with-firebase.firebaseapp.com',
    storageBucket: 'fdtcg-chat-app-with-firebase.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBChITyyXsWxM1AkOo_S-41WBbiDoLHvFI',
    appId: '1:985133492222:android:9da376d364e7807ede42af',
    messagingSenderId: '985133492222',
    projectId: 'fdtcg-chat-app-with-firebase',
    storageBucket: 'fdtcg-chat-app-with-firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAbX-lnWJwt3YQvfBeQ36OaZI4ayV18AdQ',
    appId: '1:985133492222:ios:111c9d8a8d7a2ef9de42af',
    messagingSenderId: '985133492222',
    projectId: 'fdtcg-chat-app-with-firebase',
    storageBucket: 'fdtcg-chat-app-with-firebase.appspot.com',
    iosBundleId: 'com.blogspot.lightrao.fdtcgChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAbX-lnWJwt3YQvfBeQ36OaZI4ayV18AdQ',
    appId: '1:985133492222:ios:111c9d8a8d7a2ef9de42af',
    messagingSenderId: '985133492222',
    projectId: 'fdtcg-chat-app-with-firebase',
    storageBucket: 'fdtcg-chat-app-with-firebase.appspot.com',
    iosBundleId: 'com.blogspot.lightrao.fdtcgChat',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDzHpaIfdPnG-A5a6ESchdpQbwSXHgD1EQ',
    appId: '1:985133492222:web:c21c34e247b6e222de42af',
    messagingSenderId: '985133492222',
    projectId: 'fdtcg-chat-app-with-firebase',
    authDomain: 'fdtcg-chat-app-with-firebase.firebaseapp.com',
    storageBucket: 'fdtcg-chat-app-with-firebase.appspot.com',
  );
}
